### ISSUE TITLE
Error while starting distributor and calculation_framework

### ISSUE THREAD

**Issue by duguyue100** [mil-tokyo/sashimi#3]
Hi, I'm trying to get sashimi work on my machine, I setup a dataset "sashimi" and with password "password", I also import the database.sql. After that, I try to start the distributor by running "./run.sh", however soon after it started, it gives me this error:

```
➜  distributor git:(master) sudo ./run.sh
Websocket server listening on port 64001
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
Http server listening on port 64000
assert.js:369
assert.ifError = function(err) { if (err) throw err; };
                                          ^

Error: connect ECONNREFUSED 127.0.0.1:3306
  at Object.exports._errnoException (util.js:907:11)
  at exports._exceptionWithHostPort (util.js:930:20)
  at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

    --------------------
  at Protocol._enqueue (/Users/dgyHome/Documents/workspace/sashimi/distributor/src/node_modules/mysql/lib/protocol/Protocol.js:135:48)
  at Protocol.handshake (/Users/dgyHome/Documents/workspace/sashimi/distributor/src/node_modules/mysql/lib/protocol/Protocol.js:52:41)
  at Connection.connect (/Users/dgyHome/Documents/workspace/sashimi/distributor/src/node_modules/mysql/lib/Connection.js:109:18)
  at Object.DB.getConnection (/Users/dgyHome/Documents/workspace/sashimi/distributor/src/db.js:16:15)
  at [object Object].getAndDistributeTickets (/Users/dgyHome/Documents/workspace/sashimi/distributor/src/ticket_distributor.js:192:20)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Can you see what's wrong here? Tell me what you need to know what's the problem.

**Comment by kilojapan** [comment]
Do you have MySQL installed?
You also need to check if MySQL is active and listening on port 3306.

**Comment by duguyue100** [comment]
Ok, my bad. My Mac's MySQL turns to `skip-networking` automatically.
Thanks for your help!
